### PR TITLE
Update to node-sodium@1.1.12

### PR DESCRIPTION
**Pull request by justmoon**
Upstream has advanced quite a bit (`1.0.22 -> 1.1.12`) - dunno how useful this PR is, but I figured _some_ kind of PR is better than showing up empty handed on Twitter. The whole thing is just 9e0d720 on top of the upstream tag `1.1.12`.

Main issue was dealing with the changes to the `preinstall` and `install` targets in upstream's `package.json`. Since prebuild's `--preinstall` option doesn't support arguments, I used `&&` and `||` which seems to work, but... not convinced this won't break in some situations.

Successfully tested `npm run prebuild` on Linux x64 and Win32 x64.

### CODE REVIEW

**Comment by mafintosh** [comment]
Thanks a bunch for this PR. I'll see if I can get it merged.

**Comment by ralphtheninja** [comment]
_bump_ What's the status on this?

**Comment by mafintosh** [comment]
master is now 1.1.15, mostly based on the work here

**Comment by mafintosh** [comment]
and npm published with builds for linux + mac

**Comment by dominictarr** [comment]
broken because of this:

https://github.com/paixaop/node-sodium/commit/805b6f521db3f5049b4e961a6304b8b2ded63eec#commitcomment-19350734

**Comment by mafintosh** [comment]
@dominictarr dang, should we revert?

**Comment by mafintosh** [comment]
aka, unpublish this and wait for a fix

**Comment by dominictarr** [comment]
yes I think so, I already pinned to previous version in chloride, and submitted fix.

**Comment by mafintosh** [comment]
its unpublished now. when a new upstream release is made with your PRs i'll build + release a new version here.

**Comment by justmoon** [comment]
Upstream is now merged and released: https://github.com/paixaop/node-sodium/pull/89

**Comment by justmoon** [comment]
@mafintosh @dominictarr Since the upstream fix has been merged and released in 2.0.0/2.0.1, we should be ready to try this again.

**Comment by dominictarr** [comment]
👍

**Comment by justmoon** [comment]
@mafintosh Could you give this another go? Should be ok to pull in upstream now!

**Comment by mafintosh** [comment]
@justmoon i'm a swamped atm but i can add you as owner if you want to give it a try?

**Comment by justmoon** [comment]
@mafintosh Sure, I'd be happy to.

**Comment by justmoon** [comment]
Time for the bimonthly poke!

cc/ @mafintosh

**Comment by mafintosh** [comment]
@justmoon just added you. sorry for the delay. i'm personally just using https://github.com/mafintosh/sodium-native now

**Pull request closed without merging**
